### ISSUE TITLE
d2x-v11 compatibility

### ISSUE THREAD

**Issue by impeeza** [xerpi/fakemote#26]
Hi, recently blackb0x release a new version of d2x https://github.com/davebaol/d2x-cios/releases/tag/d2x-v11-beta1, it's FakeMote compatible with it?

I personally haven't tested because my Wii is on my home and now are traveling, when back to home will make some test.

Thanks a lot for you help and great work.

**Comment by Invictaz** [comment]
Interesting find. I hope it works with it. Let us know if you tested it.

**Comment by impeeza** [comment]
Hi, I made test with several setups and works fine with the new cIOS.  thanks for your work.

even ModWii includes now.
