### ISSUE TITLE
Invalid Contentscout attribute value 

### ISSUE THREAD

**Issue by epiccatt** [xerpi/fakemote#36]
Hey, so I wanted to install fakemote on ios slot 57, but when I started the cios installer, I get this error:
Invalid contentscout attribute value 25 for the d2x-v11-beta1-vwii cIOS base 57

**Comment by xerpi** [comment]
You have to update `contentscout` according to how many `<content>` fields are inside.
Since we are adding a new module (Fakemote), you have to increase the original `contentscout` by 1.

**Comment by epiccatt** [comment]
> You have to update `contentscout` according to how many `<content>` fields are inside. Since we are adding a new module (Fakemote), you have to increase the original `contentscout` by 1.

I did that tho

**Comment by xerpi** [comment]
The error you are getting means there's a mismatch between the number of `<content>` entries and the `contentscout` value.

**Comment by epiccatt** [comment]
So i redone all the steps but i still get that error

**Comment by epiccatt** [comment]
[ciosmaps.txt](https://github.com/xerpi/fakemote/files/12908019/ciosmaps.txt)

Here is my ciosmaps file

**Comment by xerpi** [comment]
> [ciosmaps.txt](https://github.com/xerpi/fakemote/files/12908019/ciosmaps.txt)
> 
> Here is my ciosmaps file

`contentscount="26"` yet I only see 25 `<content`.

**Comment by epiccatt** [comment]
Im super confused right now, could you send me a fixed version?

**Comment by xerpi** [comment]
> Im super confused right now, could you send me a fixed version?

So for the base ios 57, your XML contains:
```xml
<base ios="57" version="6175" contentscount="26" modulescount="7">
```
But then, inside that section, there are only 25 entries
```xml
<content id="..." />
```
And none of them is actually `FAKEMOTE`.

I see that you have added the entry for `FAKEMOTE` to the base ios 56, not 57.

**Comment by xerpi** [comment]
Check this: https://github.com/davebaol/d2x-cios/releases/tag/d2x-v11-beta1-FM050

**Comment by epiccatt** [comment]
> > Im super confused right now, could you send me a fixed version?
> 
> So for the base ios 57, your XML contains:
> 
> ```
> <base ios="57" version="6175" contentscount="26" modulescount="7">
> ```
> 
> But then, inside that section, there are only 25 entries:
> 
> ```
> <content id="..." />
> ```
> 
> And none of them is actually `FAKEMOTE`.
> 
> I see that you have added the entry for `FAKEMOTE` to the base ios 56, not 57.
> 
> So you have to move:
> 
> ```
> <content id="0x24" module="FAKEMOTE" tmdmoduleid="-1"/>
> ```
> 
> To the base ios 56.

Now i understand, Thank you!

**Comment by epiccatt** [comment]
I have one more question, what cios slot should i use?

**Comment by xerpi** [comment]
> I have one more question, Where can i force a ios slot in priiloader?

Check https://wii.guide/priiloader.html#section-iii---entering-priiloader ("Holding RESET on a Wii while turning it on.")
And then Priiloader Menu > Settings > Use System Menu IOS: Off > IOS to use for SM (System Menu)
