### ISSUE TITLE
Is it possible to add bluetooth for ds4?

### ISSUE THREAD

**Issue by siegfriedgreg** [xerpi/fakemote#5]
I am not sure if the feature is in the works or if it's possible, but I found this project through your other project pairmyds4.  Thanks for releasing this! It has been working well with os58.

**Comment by xerpi** [comment]
It's technically possible, but will not be easy. Also, soon I'll have to stop working on this for at least a year, so I doubt I'll have time to add support for BT controllers.

**Comment by spielvan** [comment]
> It's technically possible, but will not be easy. Also, soon I'll have to stop working on this for at least a year, so I doubt I'll have time to add support for BT controllers.

Xerpi, do you want to hit the analog before the stop?

**Comment by siegfriedgreg** [comment]
I appreciate your response and your work. good luck with your next project.
